name: flutter_donation
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  webview_flutter: ^4.11.0
  freezed_annotation: ^3.0.0
  cached_network_image: ^3.4.1
  

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  build_runner: ^2.4.15
  flutter_gen: ^5.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
